chat/urls.py
from django.urls import path

from .views import admin_chat

urlpatterns = [
    path('', admin_chat, name='admin-chat')
]

level/urls.py
from django.urls import path

from level import views

app_name = "level"

urlpatterns = [
    path('api-level/', views.api_level, name='api-level'),
    path('buat-level/', views.buat_level, name='buat-level'),
    path('daftar-level/', views.daftar_level, name='daftar-level'),
    path('hapus-level/<str:nama_level>', views.hapus_level, name='hapus-level'),
    path('tambah-level/', views.tambah_level, name='tambah-level'),
    path('update-level/<str:nama_level>', views.update_level, name='update-level'),
]

toysrent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('level/', include('level.urls')),
    path('order/', include('order.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('review/', include('review.urls')),
    path('shipping/', include('shipping.urls')),
    path('user/', include('user.urls')),
]

level/models.py
from django.db import models

'''
Note:
- models.DO_NOTHING --> RAW SQL Integrity dan Constraint di handle
- managed = False --> RAW SQL menyatakan table , django tidak terlibat
'''
class Level(models.Model):
    nama_level = models.CharField(primary_key=True, max_length=20)
    minimum_poin = models.FloatField(null=False)
    deskripsi = models.TextField()

    class Meta:
        managed = False
        db_table = 'level_keanggotaan'
        app_label = 'level'

level/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, HttpResponseForbidden
from django.db import connection
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import json

from level.models import Level


def buat_level(request):
    url = "level/form_level_page.html"
    return render(request, url)


def api_level(request):
    c = connection.cursor()
    c.execute("SELECT * FROM level_keanggotaan;")
    result = c.fetchall()
    jsonObject = [dict(zip([key[0] for key in c.description], row))
                  for row in result]
    c.close()
    return HttpResponse(json.dumps({"data": jsonObject}), content_type="application/json")


def daftar_level(request):
    url = "level/level_page.html"
    return render(request, url)


def tambah_level(request):
    if(request.method == "POST"):
        c = connection.cursor()
        try:
            nama_level = request.POST.get('level')
            min_poin = float(request.POST.get('poin'))
            deskripsi = request.POST.get('deskripsi')
            c.execute("INSERT INTO level_keanggotaan(nama_level, minimum_poin, deskripsi) \
                 VALUES(%s, %s, %s)", [nama_level, min_poin, deskripsi])
            messages.success(request, "Berhasil menambah level")
        except:
            messages.error(request, "Maaf telah terjadi kesalahan...")
        finally:
            c.close()
        return HttpResponseRedirect(reverse('level:daftar-level'))
    else:
        return HttpResponseForbidden()

def update_level(request, nama_level):
    url = "level/update_level_page.html"
    c = connection.cursor()
    if(request.method == "POST"):
        try:
            old_nama_level = nama_level
            nama_level = request.POST.get('level')
            min_poin = float(request.POST.get('poin'))
            deskripsi = request.POST.get('deskripsi')
            c.execute("UPDATE level_keanggotaan set nama_level=%s, minimum_poin=%s,\
                 deskripsi=%s WHERE nama_level=%s", [nama_level, min_poin, deskripsi,old_nama_level])
            messages.success(request, "Berhasil update level")
        except:
            messages.error(request, "Maaf telah terjadi kesalahan...")
        finally:
            c.close()
        return HttpResponseRedirect(reverse('level:daftar-level'))

    c.execute("SELECT * FROM level_keanggotaan WHERE nama_level=%s",
        [nama_level])
    result = c.fetchall()
    jsonObject = [dict(zip([key[0] for key in c.description], row))
                  for row in result]
    c.close()
    return render(request, url, {"data": jsonObject})

@csrf_exempt
def hapus_level(request, nama_level):
    c = connection.cursor()
    try:
        c.execute(
            "DELETE FROM level_keanggotaan WHERE nama_level=%s", [nama_level])
        messages.success(request, "Berhasil menghapus level")
    except:
        messages.error(request, "Maaf telah terjadi kesalahan...")
    finally:
        c.close()
    return HttpResponseRedirect(reverse('level:daftar-level'))

    

level/templates/level/form_level_page.html
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<h3 style="text-align:center">Form Tambah Level</h3>

<div>
  <form action="{% url 'level:tambah-level' %}" method="POST">
    {% csrf_token %}
    <label for="level">Nama level: </label>
    <input type="text" id="level" name="level" placeholder="Isi nama level..." required="true" maxlength="20">

    <label for="poin">Minimum poin: </label>
    <input type="text" id="poin" name="poin" placeholder="Isi minimum poin..." required="true">

    <label for="deskripsi">Deskripsi: </label>
    <input type="text" id="deskripsi" name="deskripsi" placeholder="Isi deskripsi level...">

    <input type="submit" value="Submit">
  </form>
</div>

</body>
</html>

level/templates/level/level_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

</head>


<body>
<h3 style="text-align:center">Level Keanggotaan</h3>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<table id="level-table" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Nama level</th>
                <th>Minimum poin</th>
                <th>Deskripsi</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
</table>

</body>
<script type="text/javascript">

$(document).ready(function() {
    $('#level-table').DataTable({
        "processing": true,
        "scrollX": true,
        "ajax": {
            "url": '{% url "level:api-level" %}',
        },
        "lengthMenu": [5, 10, 25, 50],
        "order": [[1, "asc"]],
        "columns": [

            {
                data:"nama_level"

            },

            {
                data:"minimum_poin"
            },
            {
                data:"deskripsi",
                defaultContent:"<i>Tidak ada deskripsi barang</i>"
            },
            
            {   
                data:"nama_level",
                render: function ( data, type, row ) {
                    
                    return '<button><a href="/level/update-level/'+data+'">Update</a></button>'+
                           '<form action="/level/hapus-level/'+data+'" method="post">'+
                           '<button type="submit">Delete</button>'+
                           '</form>'
                }
            }          
        
        ],

        columnDefs: [
                {
                    targets: '_all',
                    className: 'dt-body-center'
                }
        ], 
    });
} );

</script>
</html>

level/templates/level/update_level_page.html
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<h3 style="text-align:center">Form Update Level</h3>

<div>
  <form action="/level/update-level/{{data.0.nama_level}}" method="POST">
    {% csrf_token %}
    <label for="level">Nama level: </label>
    <input type="text" id="level" name="level" placeholder="Isi nama level..." required="true" maxlength="20" value="{{data.0.nama_level}}">

    <label for="poin">Minimum poin: </label>
    <input type="text" id="poin"  name="poin" placeholder="Isi minimum poin..." required="true" value="{{data.0.minimum_poin}}">

    <label for="deskripsi">Deskripsi: </label>
    <input type="text" id="deskripsi" name="deskripsi" placeholder="Isi deskripsi level..." value="{{data.0.deskripsi}}">

    <input type="submit" value="Update">
  </form>
</div>
</body>
</html>